In [10]:
import pandas as pd
!pip install pandas
import matplotlib.pyplot as plt

Requirement already satisfied: pandas in c:\users\jasmi\anaconda3\lib\site-packages (1.5.3)
Requirement already satisfied: pytz>=2020.1 in c:\users\jasmi\anaconda3\lib\site-packages (from pandas) (2022.7)
Requirement already satisfied: numpy>=1.21.0 in c:\users\jasmi\anaconda3\lib\site-packages (from pandas) (1.23.5)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\jasmi\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\users\jasmi\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

# Read in Data

In [11]:
absenteeism2017_2018 = pd.read_excel(r'C:\Users\jasmi\Documents\nss\da8\projects\FINALCAPSTONE\data\chr_abs_District-Level_Suppression_2017-18.xlsx')

In [12]:
absenteeism.head()

,Year,District,District Name,Student Group,Grade Band,# Students,# Chronically Absent,% Chronically Absent
0,2018,10,Anderson County,All Students,9th through 12th,2220,436,19.6
1,2018,10,Anderson County,American Indian or Alaska Native,9th through 12th,13,**,**
2,2018,10,Anderson County,Asian,9th through 12th,17,2,11.8
3,2018,10,Anderson County,Black or African American,9th through 12th,72,24,33.3
4,2018,10,Anderson County,Black/Hispanic/Native American,9th through 12th,121,27,22.3

In [14]:
absenteeism2018_2019 = pd.read_csv(r'C:\Users\jasmi\Documents\nss\da8\projects\FINALCAPSTONE\data\district_chronic_absenteeism_2018-2019.csv')

In [15]:
absenteeism2018_2019.head()

,system,system_name,subgroup,grade_band,n_students,n_chronically_absent,pct_chronically_absent
0,10,Anderson County,All Students,9th through 12th,2167,356,16.4
1,10,Anderson County,All Students,All Grades,6164,865,14
2,10,Anderson County,All Students,K through 8th,3997,509,12.7
3,10,Anderson County,American Indian or Alaska Native,9th through 12th,9,*,*
4,10,Anderson County,American Indian or Alaska Native,All Grades,27,2,7.4

In [16]:
absenteeism2019_2020 = pd.read_csv(r'C:\Users\jasmi\Documents\nss\da8\projects\FINALCAPSTONE\data\district_chronic_absenteeism_2019-2020.csv')

In [17]:
absenteeism2019_2020.head()

,system,system_name,subgroup,grade_band,n_students,n_chronically_absent,pct_chronically_absent
0,10,Anderson County,All Students,9th through 12th,2183,412,18.9
1,10,Anderson County,All Students,All Grades,6128,989,16.1
2,10,Anderson County,All Students,K through 8th,3945,577,14.6
3,10,Anderson County,American Indian or Alaska Native,9th through 12th,11,1,9.1
4,10,Anderson County,American Indian or Alaska Native,All Grades,29,3,10.3